### PR TITLE
Messages localized to English and Chinese

### PR DESCRIPTION
**Pull request by JavierAbrego**
What do you think about setting the default language in English?

### CODE REVIEW

**Comment by pierrejochem** [comment]
Very good :-) I had the task to do the same ;-) @vaenow Have a look please ;-)

**Comment by vaenow** [comment]
Thank you for your pull request.  😄

**Comment by vaenow** [comment]
I've updated some configurations and passed my test.

Android will `automatic choose the language` depends on your phone setting.

**Comment by pierrejochem** [comment]
Very nice :-)

**Pull request merged**
