### PR TITLE
Enable usage in Android 8+

### PR DESCRIPTION
**Pull request by loban**
Android version 8 and above require new permissions in order to install external APKs. This patch does the following things:

- For Android version 8 and above, check if necessary permissions are available, and if not, launch the activity (Settings.ACTION_MANAGE_UNKNOWN_APP_SOURCES) where the user can enable the appropriate permission.
- For previous Android versions, check if necessary permissions are available, and if not, launch the activity (Settings.ACTION_SECURITY_SETTINGS) where the user can enable the appropriate permission.
- Request other necessary permissions from the user.

### CODE REVIEW

**Comment by vaenow** [comment]
Hi @loban ,

Why not use https://github.com/vaenow/cordova-plugin-app-update/issues/93#issuecomment-375275089  below, instead of changing so many code?
```bash
uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES"
```

**Comment by loban** [comment]
Thanks for the feedback. In my testing, I found that just that line alone was inadequate.

I'll try to explain why:

- REQUEST_INSTALL_PACKAGES is needed for apps targeting APIs greater than 25. In in those API versions, the app does not request permissions on app install. Instead, it has to request permissions during app running (but before the secured functions/activities are called).
- For Android O and above, for this above permission, we don't just get a dialog that asks for permissions and the user clicks yes. Instead, they have to go to a particular settings page and enable the option. So I had to write code to launch an activity that loads that page.
- Since I had to write the code for the situation above, I also wrote code to open the appropriate settings page for android versions before O (which is a different activity). This is useful in case the user had turned off "unknown sources" after installing the app.
- That is why I have two functions:
-- verifyInstallPermission() to handle installing packages (which needs to be handled differently for Android O+ and below, and which needs external activities to be launched) and 
-- verifyOtherPermissions() which shows the usual dialog requesting permissions at runtime
- And I also have all the permissions defined in plugin.xml for older android versions.

This way, this plugin works in all android versions from 4.1 jelly bean all the way to 8.1 oreo. Hope I was able to explain properly.

**Review by arthursp — APPROVED** [review]

**Comment by JoxC** [comment]
I tested the code too which works great. Maybe adding some dialog telling users what should do before setting pages prompted or just prompting the setting pages after user taped the install button may be better for user to be clear.

**Review by rupendraa — APPROVED** [review]

**Comment by egrendonDev** [comment]
Any chance the Permission fix is going to get merged in?

**Pull request merged**
