### PR TITLE
Added italian translation

### PR DESCRIPTION
**Pull request by TizioFittizio**
Let me know if this is ok

### CODE REVIEW

**Comment by carlo318** [comment]
Good TizioFittizio, I also wanted to add the italian translation.
I just suggest a modification to your proposal.
Update is not the same as Download, so IMHO you should change:
"Aggiornamento completato"  with  "Download completato"  (for "download_complete*")
and 
"Aggiorna di nuovo"   with     "Scarica di nuovo"  (for "download_complete_pos_btn")

And for "update_cancel" instead of "Cancella" I'd use  "Annulla".

**Comment by TizioFittizio** [comment]
@carlo318 thank for your feedback, i have just made the changes you proposed

**Comment by carlo318** [comment]
Perfect!

**Comment by vaenow** [comment]
Thank you guys

**Pull request merged**
